version: "3.9"
services:

  python-instance:
      hostname: pythonservice
      container_name: pythonservice
      build:
        context: .
        dockerfile: .devcontainer/python-container/Dockerfile
      volumes:
        # Mount the root folder that contains .git
        - .:/workspace:cached
      command: sleep infinity
      networks:
        - bridge-net
        
  dataimporter-instance:
      hostname: dataimporterservice
      container_name: dataimporterservice
      build:
        context: .
        dockerfile: .devcontainer/dataimporter-container/Dockerfile
      volumes:
        # Mount the root folder that contains .git
        - .:/workspace:cached
      command: sleep infinity
      networks:
        - bridge-net

  database:
    hostname: postgresdb
    container_name: postgresdb
    image: 'postgres:latest'
    ports:
      - 15432:5432
    env_file:
      - .env
    networks:
      - bridge-net
    volumes:
      - .postgresDATA/db-data/:/var/lib/postgresql/data/

  
  pgadmin:
    hostname: postgresadmin
    container_name: postgresadmin
    image: dpage/pgadmin4
    ports:
      - 15433:80
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - bridge-net
    volumes:
      - .postgresDATA/pgadmin-data/:/var/lib/pgadmin/
 





networks:
  bridge-net:
    name: bridge_network
    driver: bridge


