version: '3'

services:
  app:
    build: .
    volumes:
      - ./python_scripts:/app
    working_dir: /app
    command: sh -c "python file1.py & python file2.py & python file3.py & python file4.py & python file5.py & python file6.py & python script1.py && python script2.py && python script3.py"
