version: "3.9"
services:
  app:
      build:
          context: ..
          dockerfile: .devcontainer/Dockerfile
          args:
            - VARIANT=${RUST_VARIANT}
      volumes:
          - ..:/workspace
      user: ${UBUNTU_USER}
      command: sleep infinity

  scylla-db:
    hostname: rabbitmq
    container_name: scylla
    image: "scylladb/scylla"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_User}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_Pass}
    ports:
      - ${Syclla_Mainport}:9042
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9180:9180
      - 9160:9160
      - 10000:10000
    networks:
      - bridge-net


networks:
  bridge-net:
    name: bridge_network
    driver: bridge


